name: sports_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  share_plus: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  palette_generator: ^0.3.3+4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  intl_utils: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Ensure the following line is included if using localization files:
  generate: true
  