name: graduation_project_iti
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  geocoding: ^2.0.0
  provider: ^6.1.2
  cached_network_image: ^3.2.0
  google_fonts: ^6.2.1
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  share_plus: ^9.0.0
  palette_generator: ^0.3.3+4
  shared_preferences: ^2.0.11
  google_sign_in: ^5.0.7
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  generate: true
